# https://github.com/rfonod/stabilo-optimize

clahe: false  
downsample_ratio: 0.5  

detector_name: 'orb'  
max_features: 2000  
ref_multiplier: 2.0  

matcher_name: 'bf'  
filter_type: 'ratio'  
filter_ratio: 0.9  

transformation_type: 'projective'  
ransac_method: 38  
ransac_epipolar_threshold: 2.0  
ransac_max_iter: 5000  
ransac_confidence: 0.999999  

mask_use: true  
mask_margin_ratio: 0.15  

brisk_threshold: 130  
kaze_threshold: 0.01  
akaze_threshold: 0.01  

gpu: false

viz: false  
benchmark: false  

min_good_match_count_warning: 20  
min_inliers_match_count_warning: 10  